const types = {
  SET_SOURCE: 'path/SET_SOURCE',
  SET_DESTINATION: 'path/SET_DESTINATION',
  SET_FILTER: 'path/SET_FILTER',
  SET_LOCATIONS: 'path/SET_LOCATIONS',
  START_SEARCH: 'path/START_SEARCH',
  SEARCH_SUCCESS: 'path/SEARCH_SUCCESS',
};

export default types;
